apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: llm-route
spec:
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: kaito-gateway
  rules:
  - matches:
    - headers:
      - type: Exact
        name: X-Gateway-Model-Name
        value: phi-4-mini-instruct
      path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: wks-phi-4-mini-instruct-inferencepool
      group: inference.networking.k8s.io
      kind: InferencePool
  - matches:
    - headers:
      - type: Exact
        name: X-Gateway-Model-Name
        value: gpt-oss-20b
      path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: wks-gpt-oss-20b-inferencepool
      group: inference.networking.k8s.io
      kind: InferencePool
  - matches:
    - path:
        type: PathPrefix
        value: /rag
    filters:
    - type: URLRewrite
      urlRewrite:
        path:
          type: ReplacePrefixMatch
          replacePrefixMatch: /v1
    backendRefs:
    - name: rag-gpt-oss-20b
      port: 80