apiVersion: v1
kind: ConfigMap
metadata:
  name: gpt-oss-20b-config
data:
  inference_config.yaml: |
    vllm:
      gpu-memory-utilization: 0.82  # Controls GPU memory usage (0.0-1.0)
---
apiVersion: kaito.sh/v1beta1
kind: Workspace
metadata:
  name: wks-gpt-oss-20b
resource:
  instanceType: Standard_NC24ads_A100_v4
  labelSelector:
    matchLabels:
      apps: gpt-oss-20b
inference:
  preset:
    name: gpt-oss-20b
  config: gpt-oss-20b-config
