apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- agent.yaml
- web.yaml
- istio-httprule-web.yaml
configMapGenerator:
- behavior: create
  envs:
  - .env.agent
  name: agent-env
- behavior: create
  envs:
  - .env.web
  name: web-env
