apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
- ../kaito-chat-app
labels:
- pairs:
    app.kubernetes.io/managed-by: kustomize
    environment: prod
configMapGenerator:
- behavior: replace
  envs:
  - .env.agent
  name: agent-env
- behavior: replace
  envs:
  - .env.web
  name: web-env
