apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- otel-collector.yaml
- loki.yaml
- tempo.yaml
- prometheus.yaml
- grafana.yaml
- redis.yaml
labels:
- pairs:
    app.kubernetes.io/managed-by: kustomize
