apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
configurations:
- kustomconfig.yaml
resources:
- argo-workflowtemplate.yaml
labels:
- pairs:
    app.kubernetes.io/managed-by: kustomize
    environment: prod
